### PR TITLE
Removed Crashlytics and references to maven.io

### PR DESCRIPTION
**Pull request by samtinel**
This PR removes Crashlytics and reference to maven.io. This means it is buildable by F-Droid. To be included, metadata has to be added, see #17 .

### CODE REVIEW

**Comment by lloydtorres** [comment]
Thanks so much for digging into this!

Per the [commit that implemented Crashlytics](https://github.com/lloydtorres/stately/commit/786a12a99db8ce4baac2a3c3b3ae523cedfe7a15), you'll also need to remove the `app/fabric.properties` file and the `io.fabric.ApiKey` metadata tag from the manifest. Would you mind updating your pull request with those changes?

Also, would you like to be added to the [contributors list](https://github.com/lloydtorres/stately/blob/master/Stately/app/src/main/res/values/strings.xml#L551)? If so, what name would you prefer for that? I'll make a separate commit to add you in once the pull request is merged in.

**Comment by sarthon** [comment]
updated the PR with the new changes, but please do not merge yet, tomorrow I will test more thoroughly
> Also, would you like to be added to the contributors list?
yes, thanks! use "Samtinel" please

**Comment by samtinel** [comment]
It currently doesn't build for me, I think because of some gradle versioning stuff? But it might also be because I haven't configured it correctly on this new env. will report back

**Comment by samtinel** [comment]
Ah, interesting. Apparently [Gradle](https://github.com/gradle/gradle/issues/12599) has to be >= 6.3 to work with JDK 14. Downgrading java fixed that. Building works.

**Comment by samtinel** [comment]
It runs also fine through the smoke test. What I wonder is if the switch "send crash reports" also needs removal. Will  dig into it in the following days.

**Comment by lloydtorres** [comment]
Good catch, definitely get rid of that switch while you're at it.

**Comment by samtinel** [comment]
Removed the toggle and its resources, as well as the mention of CrashLytics in the readme. It compiles and passes the smoke test.
So in my eyes this is ready to merge, and then the last hurdle is #17. After that maybe a minor version bump?

**Comment by lloydtorres** [comment]
This pull request LGTM, thanks so much for doing this!

We can handle blocking changes related to F-Droid in #17.

**Pull request merged**
